open_graph_image_width: 1200
open_graph_image_height: 1200

defaults:
  title: '@seo:title'
  description: '@seo:content'
humans:
  enabled: true
  content: |
    /* TEAM */

    Creator: {{ site_name }}
    URL: {{ site_url }}
    Description: {{ description }}

    /* THANKS */

    Statamic: https://statamic.com

    /* SITE */

    Standards: HTML5, CSS3
    Components: Statamic 2, Laravel, PHP, JavaScript
